### ISSUE TITLE
get_Logger does not have an implementation, when trying to Unit Test the plugin with Plugin Telemetry

### ISSUE THREAD

**Issue by AkhileshKhoday** [DynamicsValue/fake-xrm-easy-samples#13]
**Method 'get_Logger' in type 'FakeXrmEasy.Plugins.XrmFakedPluginContextProperties' from assembly 'FakeXrmEasy.Plugins, Version=2.1.1.0, Culture=neutral, PublicKeyToken=d91a65dda907a34f' does not have an implementation.'**

I am using FakeXrmEasy.v9 Version 2.1.2

**My Middle ware as below**

using System;
using System.Reflection;
using Microsoft.Xrm.Sdk;
using FakeXrmEasy.Abstractions;
using FakeXrmEasy.Abstractions.Enums;
using FakeXrmEasy.FakeMessageExecutors;
using FakeXrmEasy.Middleware;
using FakeXrmEasy.Middleware.Crud;
using FakeXrmEasy.Middleware.Messages;
using Castle.Core.Logging;
using Moq;

namespace UnitTests
{
    public class FakeXrmEasyTestBase
    {
        protected readonly IOrganizationService _service;
        protected readonly IXrmFakedContext _context;
        protected readonly Mock<IServiceProvider> _serviceProviderMock;
        protected readonly Mock<ILogger> _loggerMock;

        public FakeXrmEasyTestBase()
        {
            _context = MiddlewareBuilder
            .New()
            .AddCrud()
            .AddFakeMessageExecutors(Assembly.GetAssembly(typeof(AddListMembersListRequestExecutor)))
            .UseCrud()
            .UseMessages()
            .SetLicense(FakeXrmEasyLicense.NonCommercial)
            .Build();
            _service = _context.GetOrganizationService();
        }
    }
}

**UT as below**

public class PluginWithTelemetryTest : FakeXrmEasyTestBase
{
	[TestMethod]
	 public void TestTelemetryPlugin()
	 {
		_context.ExecutePluginWithTarget<LoggerPlugin>();
	 }
}

**Plugin as below**

public class LoggerPlugin : IPlugin
{
	public void Execute(IServiceProvider serviceProvider)
	{
		var logger = serviceProvider.Get<ILogger>();
		logger.LogInformation("Test");
	}
}

**Comment by jordimontana82** [comment]
Hi @AkhileshKhoday  It looks like you're overriding your own service provider with Moq. When you using FakeXrmEasy there is no need to use Moq at all, FakeXrmEasy takes care of it.

Please take a look at these sample unit tests that demonstrate both the OOB logger implementation or even a custom one:

https://github.com/DynamicsValue/fake-xrm-easy-plugins/blob/9718dcc55e4db369657f620ff87ac269eb80499f/tests/FakeXrmEasy.Plugins.Tests/Services/ILoggerTests.cs#L9-L34

**Comment by AkhileshKhoday** [comment]
Hi @jordimontana82, thank you for the quick response, I am able to Unit Test the plugin with Plugin Telemetry.

**Comment by AkhileshKhoday** [comment]
@jordimontana82, thanks for the quick response, I am able to Unit Test the plugin with Plugin Telemetry.
